version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432
    environment:
      POSTGRES_USER: chimera
      POSTGRES_PASSWORD: chimera
    healthcheck:
      test: pg_isready -U chimera -h 127.0.0.1
      interval: 5s
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/chimera
    ports:
      - 3000
    environment:
      POSTGRES_USER: chimera
      POSTGRES_PASSWORD: chimera
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
  webserver:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - app:app
