default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { 5 } %>
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>

development:
  <<: *default
  database: chimera_development

test:
  <<: *default
  database: chimera_test

production:
  <<: *default
  database: chimera_production
  username: chimera
  password: <%= ENV['CHIMERA_DATABASE_PASSWORD'] %>
